name: NodeJS with Webpack

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: Deployment
        run: |
          ssh-keyscan 13.53.130.120 >> ~/.ssh/known_hosts
          scp -r -i {{ secrets.SSH_KEY }} build ubuntu@13.53.130.120:/react-production
