name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: Connection setup
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-aws
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host aws
              HostName 13.53.130.120
              User ubuntu
              IdentityFile ~/.ssh/id_rsa-aws
      - name: Deployment
        run: |
          sudo scp -r build 13.53.130.120:/var/www/react-production
