name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  SERVER_HOST: 13.53.130.120
  SERVER_USER: ubuntu
  SERVER_PATH: /var/www/react-production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing packages
        run: npm ci
      - name: Building
        run: npm run build:prod
      - name: Linting typescript
        run: npm run list:ts
      - name: Linting css
        run: npm run list:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Authorization
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Deployment
        run: |
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
          scp -r build/* ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
