name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: Connection setup
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: 13.53.130.120
          username: ubuntu
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.SSH_KEY}}
      - name: Deployment
        run: |
          sudo scp -r build/ ubuntu@13.53.130.120:/var/www/react-production
